USE wechat_oa;

CREATE TABLE `wechat_oa_account` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` bigint(20) NOT NULL COMMENT '租户ID',
  `account_name` varchar(128) NOT NULL COMMENT '公众号名称',
  `app_id` varchar(64) NOT NULL COMMENT '微信AppID',
  `app_secret` varchar(128) NOT NULL COMMENT '微信AppSecret(加密存储)',
  `token` varchar(128) DEFAULT NULL COMMENT '微信Token',
  `aes_key` varchar(128) DEFAULT NULL COMMENT '消息加密密钥',
  `account_type` tinyint(4) NOT NULL DEFAULT 0 COMMENT '类型 0-订阅号 1-服务号',
  `is_verified` tinyint(4) NOT NULL DEFAULT 0 COMMENT '是否认证 0-否 1-是',
  `qr_code_url` varchar(512) DEFAULT NULL COMMENT '公众号二维码URL',
  `access_token` varchar(512) DEFAULT NULL COMMENT '当前AccessToken(加密存储)',
  `access_token_expire_time` datetime DEFAULT NULL COMMENT 'AccessToken过期时间',
  `status` tinyint(4) NOT NULL DEFAULT 1 COMMENT '状态 0-禁用 1-启用',
  `create_user_id` varchar(64) DEFAULT NULL COMMENT '创建人ID',
  `create_user_name` varchar(64) DEFAULT NULL COMMENT '创建人姓名',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_user_id` varchar(64) DEFAULT NULL COMMENT '更新人ID',
  `update_user_name` varchar(64) DEFAULT NULL COMMENT '更新人姓名',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `delete_flag` int(11) NOT NULL DEFAULT 0 COMMENT '删除标记',
  `data_version` int(11) NOT NULL DEFAULT 0 COMMENT '数据版本号',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_app_id` (`app_id`),
  KEY `idx_tenant` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='公众号账号表';

CREATE TABLE `wechat_oa_material` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` bigint(20) NOT NULL COMMENT '租户ID',
  `account_id` bigint(20) NOT NULL COMMENT '公众号ID',
  `media_id` varchar(128) DEFAULT NULL COMMENT '微信素材MediaID',
  `material_type` tinyint(4) NOT NULL COMMENT '类型 0-图片 1-语音 2-视频 3-缩略图',
  `title` varchar(256) DEFAULT NULL COMMENT '素材标题',
  `file_name` varchar(256) DEFAULT NULL COMMENT '原始文件名',
  `file_url` varchar(512) DEFAULT NULL COMMENT '本地存储URL(MinIO)',
  `file_size` bigint(20) DEFAULT NULL COMMENT '文件大小(字节)',
  `wechat_url` varchar(512) DEFAULT NULL COMMENT '微信端URL',
  `create_user_id` varchar(64) DEFAULT NULL COMMENT '创建人ID',
  `create_user_name` varchar(64) DEFAULT NULL COMMENT '创建人姓名',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_user_id` varchar(64) DEFAULT NULL COMMENT '更新人ID',
  `update_user_name` varchar(64) DEFAULT NULL COMMENT '更新人姓名',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `delete_flag` int(11) NOT NULL DEFAULT 0 COMMENT '删除标记',
  `data_version` int(11) NOT NULL DEFAULT 0 COMMENT '数据版本号',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_account` (`tenant_id`, `account_id`),
  KEY `idx_media_id` (`media_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='素材表';

CREATE TABLE `wechat_oa_article` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` bigint(20) NOT NULL COMMENT '租户ID',
  `account_id` bigint(20) NOT NULL COMMENT '公众号ID',
  `title` varchar(256) NOT NULL COMMENT '标题',
  `author` varchar(64) DEFAULT NULL COMMENT '作者',
  `digest` varchar(512) DEFAULT NULL COMMENT '摘要',
  `content` mediumtext COMMENT '正文(HTML)',
  `thumb_media_id` varchar(128) DEFAULT NULL COMMENT '封面素材ID',
  `thumb_url` varchar(512) DEFAULT NULL COMMENT '封面URL',
  `content_source_url` varchar(512) DEFAULT NULL COMMENT '原文链接',
  `wx_media_id` varchar(128) DEFAULT NULL COMMENT '微信端图文素材ID',
  `status` tinyint(4) NOT NULL DEFAULT 0 COMMENT '状态 0-草稿 1-已发布 2-已下线',
  `publish_time` datetime DEFAULT NULL COMMENT '发布时间',
  `read_count` int(11) NOT NULL DEFAULT 0 COMMENT '阅读数',
  `share_count` int(11) NOT NULL DEFAULT 0 COMMENT '分享数',
  `like_count` int(11) NOT NULL DEFAULT 0 COMMENT '点赞数',
  `sort_order` int(11) NOT NULL DEFAULT 0 COMMENT '多图文排序',
  `create_user_id` varchar(64) DEFAULT NULL COMMENT '创建人ID',
  `create_user_name` varchar(64) DEFAULT NULL COMMENT '创建人姓名',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_user_id` varchar(64) DEFAULT NULL COMMENT '更新人ID',
  `update_user_name` varchar(64) DEFAULT NULL COMMENT '更新人姓名',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `delete_flag` int(11) NOT NULL DEFAULT 0 COMMENT '删除标记',
  `data_version` int(11) NOT NULL DEFAULT 0 COMMENT '数据版本号',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_account` (`tenant_id`, `account_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='图文表';

CREATE TABLE `wechat_oa_fan_user` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` bigint(20) NOT NULL COMMENT '租户ID',
  `account_id` bigint(20) NOT NULL COMMENT '公众号ID',
  `openid` varchar(64) NOT NULL COMMENT '微信OpenID',
  `unionid` varchar(64) DEFAULT NULL COMMENT '微信UnionID',
  `nickname` varchar(128) DEFAULT NULL COMMENT '昵称',
  `avatar_url` varchar(512) DEFAULT NULL COMMENT '头像URL',
  `gender` tinyint(4) DEFAULT 0 COMMENT '性别 0-未知 1-男 2-女',
  `country` varchar(64) DEFAULT NULL COMMENT '国家',
  `province` varchar(64) DEFAULT NULL COMMENT '省份',
  `city` varchar(64) DEFAULT NULL COMMENT '城市',
  `language` varchar(32) DEFAULT NULL COMMENT '语言',
  `subscribe_status` tinyint(4) NOT NULL DEFAULT 1 COMMENT '关注状态 0-已取关 1-已关注',
  `subscribe_time` datetime DEFAULT NULL COMMENT '关注时间',
  `unsubscribe_time` datetime DEFAULT NULL COMMENT '取关时间',
  `subscribe_scene` varchar(64) DEFAULT NULL COMMENT '关注渠道',
  `is_blacklisted` tinyint(4) NOT NULL DEFAULT 0 COMMENT '是否拉黑 0-否 1-是',
  `tag_ids` varchar(512) DEFAULT NULL COMMENT '标签ID列表(JSON)',
  `create_user_id` varchar(64) DEFAULT NULL COMMENT '创建人ID',
  `create_user_name` varchar(64) DEFAULT NULL COMMENT '创建人姓名',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_user_id` varchar(64) DEFAULT NULL COMMENT '更新人ID',
  `update_user_name` varchar(64) DEFAULT NULL COMMENT '更新人姓名',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `delete_flag` int(11) NOT NULL DEFAULT 0 COMMENT '删除标记',
  `data_version` int(11) NOT NULL DEFAULT 0 COMMENT '数据版本号',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_account_openid` (`account_id`, `openid`),
  KEY `idx_tenant_account` (`tenant_id`, `account_id`),
  KEY `idx_subscribe` (`subscribe_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='粉丝表';

CREATE TABLE `wechat_oa_user_tag` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` bigint(20) NOT NULL COMMENT '租户ID',
  `account_id` bigint(20) NOT NULL COMMENT '公众号ID',
  `wx_tag_id` int(11) DEFAULT NULL COMMENT '微信端标签ID',
  `tag_name` varchar(64) NOT NULL COMMENT '标签名称',
  `fan_count` int(11) NOT NULL DEFAULT 0 COMMENT '粉丝数',
  `create_user_id` varchar(64) DEFAULT NULL COMMENT '创建人ID',
  `create_user_name` varchar(64) DEFAULT NULL COMMENT '创建人姓名',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_user_id` varchar(64) DEFAULT NULL COMMENT '更新人ID',
  `update_user_name` varchar(64) DEFAULT NULL COMMENT '更新人姓名',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `delete_flag` int(11) NOT NULL DEFAULT 0 COMMENT '删除标记',
  `data_version` int(11) NOT NULL DEFAULT 0 COMMENT '数据版本号',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_account` (`tenant_id`, `account_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='粉丝标签表';

CREATE TABLE `wechat_oa_auto_reply_rule` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` bigint(20) NOT NULL COMMENT '租户ID',
  `account_id` bigint(20) NOT NULL COMMENT '公众号ID',
  `rule_name` varchar(128) NOT NULL COMMENT '规则名称',
  `rule_type` tinyint(4) NOT NULL COMMENT '类型 0-关注回复 1-关键词回复 2-默认回复',
  `keyword` varchar(256) DEFAULT NULL COMMENT '关键词',
  `match_type` tinyint(4) DEFAULT NULL COMMENT '匹配方式 0-全匹配 1-半匹配',
  `reply_type` tinyint(4) NOT NULL COMMENT '回复类型 0-文本 1-图片 2-图文',
  `reply_content` text COMMENT '回复内容',
  `reply_media_id` varchar(128) DEFAULT NULL COMMENT '回复素材ID',
  `status` tinyint(4) NOT NULL DEFAULT 1 COMMENT '状态 0-禁用 1-启用',
  `sort_order` int(11) NOT NULL DEFAULT 0 COMMENT '排序',
  `create_user_id` varchar(64) DEFAULT NULL COMMENT '创建人ID',
  `create_user_name` varchar(64) DEFAULT NULL COMMENT '创建人姓名',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_user_id` varchar(64) DEFAULT NULL COMMENT '更新人ID',
  `update_user_name` varchar(64) DEFAULT NULL COMMENT '更新人姓名',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `delete_flag` int(11) NOT NULL DEFAULT 0 COMMENT '删除标记',
  `data_version` int(11) NOT NULL DEFAULT 0 COMMENT '数据版本号',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_account_type` (`tenant_id`, `account_id`, `rule_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='自动回复规则表';

CREATE TABLE `wechat_oa_menu` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` bigint(20) NOT NULL COMMENT '租户ID',
  `account_id` bigint(20) NOT NULL COMMENT '公众号ID',
  `menu_name` varchar(64) NOT NULL COMMENT '菜单名称',
  `parent_id` bigint(20) NOT NULL DEFAULT 0 COMMENT '父菜单ID 0-一级',
  `menu_type` varchar(32) NOT NULL COMMENT '菜单类型 click/view/miniprogram等',
  `menu_key` varchar(128) DEFAULT NULL COMMENT '菜单KEY(click类型)',
  `menu_url` varchar(512) DEFAULT NULL COMMENT '菜单URL(view类型)',
  `media_id` varchar(128) DEFAULT NULL COMMENT '素材ID',
  `sort_order` int(11) NOT NULL DEFAULT 0 COMMENT '排序',
  `create_user_id` varchar(64) DEFAULT NULL COMMENT '创建人ID',
  `create_user_name` varchar(64) DEFAULT NULL COMMENT '创建人姓名',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_user_id` varchar(64) DEFAULT NULL COMMENT '更新人ID',
  `update_user_name` varchar(64) DEFAULT NULL COMMENT '更新人姓名',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `delete_flag` int(11) NOT NULL DEFAULT 0 COMMENT '删除标记',
  `data_version` int(11) NOT NULL DEFAULT 0 COMMENT '数据版本号',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_account` (`tenant_id`, `account_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='公众号菜单表';
