USE workflow;

CREATE TABLE `wf_process_definition_ext` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` bigint(20) NOT NULL COMMENT '租户ID',
  `process_definition_id` varchar(128) NOT NULL DEFAULT '' COMMENT 'Flowable流程定义ID',
  `process_key` varchar(128) NOT NULL COMMENT '流程标识',
  `process_name` varchar(256) NOT NULL COMMENT '流程名称',
  `category` varchar(64) DEFAULT NULL COMMENT '分类',
  `icon` varchar(512) DEFAULT NULL COMMENT '流程图标URL',
  `description` varchar(1024) DEFAULT NULL COMMENT '流程说明',
  `form_type` tinyint(4) NOT NULL DEFAULT 0 COMMENT '表单类型 0-外链 1-内嵌JSON',
  `form_url` varchar(512) DEFAULT NULL COMMENT '表单URL',
  `form_config` text COMMENT '表单配置(JSON)',
  `is_template` tinyint(4) NOT NULL DEFAULT 0 COMMENT '是否平台模板 0-自定义 1-模板',
  `version` int(11) NOT NULL DEFAULT 1 COMMENT '版本号',
  `status` tinyint(4) NOT NULL DEFAULT 1 COMMENT '状态 0-挂起 1-激活',
  `sort_order` int(11) NOT NULL DEFAULT 0 COMMENT '排序',
  `model_id` varchar(64) DEFAULT NULL COMMENT 'Flowable Model ID',
  `create_user_id` varchar(64) DEFAULT NULL COMMENT '创建人ID',
  `create_user_name` varchar(64) DEFAULT NULL COMMENT '创建人姓名',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_user_id` varchar(64) DEFAULT NULL COMMENT '更新人ID',
  `update_user_name` varchar(64) DEFAULT NULL COMMENT '更新人姓名',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `delete_flag` int(11) NOT NULL DEFAULT 0 COMMENT '删除标记',
  `data_version` int(11) NOT NULL DEFAULT 0 COMMENT '数据版本号',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_key` (`tenant_id`, `process_key`),
  KEY `idx_flowable_def_id` (`process_definition_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流程定义扩展表';

CREATE TABLE `wf_process_instance_ext` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` bigint(20) NOT NULL COMMENT '租户ID',
  `process_instance_id` varchar(128) NOT NULL COMMENT 'Flowable流程实例ID',
  `process_definition_id` varchar(128) NOT NULL COMMENT 'Flowable流程定义ID',
  `process_key` varchar(128) DEFAULT NULL COMMENT '流程标识',
  `process_name` varchar(256) DEFAULT NULL COMMENT '流程名称',
  `title` varchar(256) DEFAULT NULL COMMENT '流程标题',
  `initiator_id` bigint(20) NOT NULL COMMENT '发起人ID',
  `initiator_name` varchar(64) DEFAULT NULL COMMENT '发起人姓名',
  `initiator_dept_id` bigint(20) DEFAULT NULL COMMENT '发起人部门ID',
  `business_key` varchar(256) DEFAULT NULL COMMENT '业务关联键',
  `form_data` text COMMENT '表单数据(JSON)',
  `status` tinyint(4) NOT NULL DEFAULT 0 COMMENT '状态 0-进行中 1-已完成 2-已撤回 3-已终止',
  `result` tinyint(4) DEFAULT NULL COMMENT '结果 1-通过 2-驳回',
  `end_time` datetime DEFAULT NULL COMMENT '结束时间',
  `duration` bigint(20) DEFAULT NULL COMMENT '耗时(ms)',
  `create_user_id` varchar(64) DEFAULT NULL COMMENT '创建人ID',
  `create_user_name` varchar(64) DEFAULT NULL COMMENT '创建人姓名',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_user_id` varchar(64) DEFAULT NULL COMMENT '更新人ID',
  `update_user_name` varchar(64) DEFAULT NULL COMMENT '更新人姓名',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `delete_flag` int(11) NOT NULL DEFAULT 0 COMMENT '删除标记',
  `data_version` int(11) NOT NULL DEFAULT 0 COMMENT '数据版本号',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_instance_id` (`process_instance_id`),
  KEY `idx_tenant_initiator` (`tenant_id`, `initiator_id`),
  KEY `idx_tenant_status` (`tenant_id`, `status`),
  KEY `idx_tenant_time` (`tenant_id`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流程实例扩展表';

CREATE TABLE `wf_task_ext` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` bigint(20) NOT NULL COMMENT '租户ID',
  `task_id` varchar(128) NOT NULL COMMENT 'Flowable任务ID',
  `process_instance_id` varchar(128) NOT NULL COMMENT '流程实例ID',
  `task_name` varchar(256) DEFAULT NULL COMMENT '任务名称',
  `assignee_id` bigint(20) DEFAULT NULL COMMENT '当前处理人ID',
  `assignee_name` varchar(64) DEFAULT NULL COMMENT '当前处理人姓名',
  `owner_id` bigint(20) DEFAULT NULL COMMENT '任务所有人ID',
  `action` tinyint(4) DEFAULT NULL COMMENT '操作 1-通过 2-驳回 3-转办 4-委派 5-加签',
  `comment` varchar(2048) DEFAULT NULL COMMENT '审批意见',
  `duration` bigint(20) DEFAULT NULL COMMENT '处理耗时(ms)',
  `complete_time` datetime DEFAULT NULL COMMENT '完成时间',
  `create_user_id` varchar(64) DEFAULT NULL COMMENT '创建人ID',
  `create_user_name` varchar(64) DEFAULT NULL COMMENT '创建人姓名',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_user_id` varchar(64) DEFAULT NULL COMMENT '更新人ID',
  `update_user_name` varchar(64) DEFAULT NULL COMMENT '更新人姓名',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `delete_flag` int(11) NOT NULL DEFAULT 0 COMMENT '删除标记',
  `data_version` int(11) NOT NULL DEFAULT 0 COMMENT '数据版本号',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_task_id` (`task_id`),
  KEY `idx_tenant_assignee` (`tenant_id`, `assignee_id`),
  KEY `idx_instance_id` (`process_instance_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='任务扩展表';

CREATE TABLE `wf_copy` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` bigint(20) NOT NULL COMMENT '租户ID',
  `process_instance_id` varchar(128) NOT NULL COMMENT '流程实例ID',
  `process_name` varchar(256) DEFAULT NULL COMMENT '流程名称',
  `title` varchar(256) DEFAULT NULL COMMENT '流程标题',
  `initiator_id` bigint(20) NOT NULL COMMENT '发起人ID',
  `initiator_name` varchar(64) DEFAULT NULL COMMENT '发起人姓名',
  `receiver_id` bigint(20) NOT NULL COMMENT '接收人ID',
  `receiver_name` varchar(64) DEFAULT NULL COMMENT '接收人姓名',
  `task_name` varchar(256) DEFAULT NULL COMMENT '发生在哪个节点',
  `is_read` tinyint(4) NOT NULL DEFAULT 0 COMMENT '是否已读 0-未读 1-已读',
  `read_time` datetime DEFAULT NULL COMMENT '阅读时间',
  `create_user_id` varchar(64) DEFAULT NULL COMMENT '创建人ID',
  `create_user_name` varchar(64) DEFAULT NULL COMMENT '创建人姓名',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_user_id` varchar(64) DEFAULT NULL COMMENT '更新人ID',
  `update_user_name` varchar(64) DEFAULT NULL COMMENT '更新人姓名',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `delete_flag` int(11) NOT NULL DEFAULT 0 COMMENT '删除标记',
  `data_version` int(11) NOT NULL DEFAULT 0 COMMENT '数据版本号',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_receiver` (`tenant_id`, `receiver_id`, `is_read`),
  KEY `idx_instance_id` (`process_instance_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流程抄送表';

CREATE TABLE `wf_node_config` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` bigint(20) NOT NULL COMMENT '租户ID',
  `process_definition_id` varchar(128) NOT NULL COMMENT '流程定义ID',
  `node_id` varchar(128) NOT NULL COMMENT 'BPMN节点ID',
  `node_name` varchar(256) DEFAULT NULL COMMENT '节点名称',
  `assignee_type` tinyint(4) NOT NULL COMMENT '审批人类型 1-指定用户 2-指定角色 3-部门负责人 4-发起人自选',
  `assignee_ids` varchar(1024) DEFAULT NULL COMMENT '审批人/角色ID列表(JSON)',
  `approval_mode` tinyint(4) NOT NULL DEFAULT 1 COMMENT '审批模式 1-或签 2-会签 3-依次',
  `create_user_id` varchar(64) DEFAULT NULL COMMENT '创建人ID',
  `create_user_name` varchar(64) DEFAULT NULL COMMENT '创建人姓名',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_user_id` varchar(64) DEFAULT NULL COMMENT '更新人ID',
  `update_user_name` varchar(64) DEFAULT NULL COMMENT '更新人姓名',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `delete_flag` int(11) NOT NULL DEFAULT 0 COMMENT '删除标记',
  `data_version` int(11) NOT NULL DEFAULT 0 COMMENT '数据版本号',
  `remark` varchar(512) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_def_node` (`process_definition_id`, `node_id`),
  KEY `idx_tenant` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流程节点审批人配置表';
