server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway
  config:
    import:
      - optional:nacos:gateway.yml
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:123456}
  boot:
    admin:
      client:
        url: http://${SBA_HOST:localhost}:9090
        instance:
          prefer-ip: true
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:e96d2e6b-7bf3-4a42-973a-e020a213cde2}
      config:
        server-addr: ${NACOS_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:e96d2e6b-7bf3-4a42-973a-e020a213cde2}
        file-extension: yml
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: platform-service
          uri: lb://platform-service
          predicates:
            - Path=/api/platform/**
          filters:
            - StripPrefix=2

        - id: rbac-service
          uri: lb://rbac-service
          predicates:
            - Path=/api/rbac/**
          filters:
            - StripPrefix=2

        - id: workflow-service
          uri: lb://workflow-service
          predicates:
            - Path=/api/workflow/**
          filters:
            - StripPrefix=2

        - id: wechat-oa-service
          uri: lb://wechat-oa-service
          predicates:
            - Path=/api/wechat-oa/**
          filters:
            - StripPrefix=2

        - id: notify-service
          uri: lb://notify-service
          predicates:
            - Path=/api/notify/**
          filters:
            - StripPrefix=2

        - id: code-generator
          uri: lb://code-generator
          predicates:
            - Path=/api/generator/**
          filters:
            - StripPrefix=2

sa-token:
  token-name: Authorization
  token-prefix: Bearer
  timeout: 604800
  active-timeout: 7200
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: false

knife4j:
  gateway:
    enabled: true
    strategy: discover
    discover:
      enabled: true
      version: openapi3

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:localhost}:9411/api/v2/spans
