server:
  port: 8084

spring:
  application:
    name: platform-service
  config:
    import:
      - optional:nacos:platform-service.yml
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/platform?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:123456}
  kafka:
    bootstrap-servers: ${KAFKA_ADDR:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:e96d2e6b-7bf3-4a42-973a-e020a213cde2}
      config:
        server-addr: ${NACOS_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:e96d2e6b-7bf3-4a42-973a-e020a213cde2}
        file-extension: yml

sa-token:
  token-name: Authorization
  token-prefix: Bearer
  timeout: 604800
  active-timeout: 7200
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: false

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      logic-delete-field: deleteFlag
      logic-delete-value: 1
      logic-not-delete-value: 0

xxl:
  job:
    admin-addresses: http://127.0.0.1:8088/xxl-job-admin
    executor-appname: platform-service
    executor-port: 0
